<?php


namespace app\controllers;




use app\models\Activity;
use yii\filters\auth\HttpBearerAuth;
use yii\rest\ActiveController;

//use yii\rest\Controller;
// class ActivityRestController extends yii\rest\Controller  //если хотим содать какую-то сущность

/**
 * Class ActivityRestController
 * @package app\controllers
 * использует сущность Activity с ActiveRecord
 */
class ActivityRestController extends ActiveController
{
    public $modelClass = Activity::class;

    /**
     * @return array|void
     */
    public function behaviors()
    {
       // return parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors = parent::behaviors();

        /**
         * аутентификация
         */
        $behaviors['authenticator']['class'] = HttpBearerAuth::class;

        return $behaviors;
    }

}