<?php
/**
 * Created by PhpStorm.
 * User: pravl
 * Date: 24.01.2019
 * Time: 21:50
 */

namespace app\models;




use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * Class Activity
 * @package app\models
 * Сущность события,  хранимого в календаре
 */
class Activity extends ActivityBase
{
    /**
     * дата начала события в формате 'Y-m-d'
     * @var string $date_activity
     */
    public $date_activity;

    /**
     * временная пока организую классы картинок
     * @var $picture array
     */
    public $picture;

    /**
     *  временная пока не организую классы документов
     * @var $document string
     */
    public $document;

    /**
     * вспомогательная переменная
     * @var $array_errors array
     */
    public $array_errors = [];

    /**
     * спомогательная временная, пока не разберусь, как устройить привязку документов и фото
     * @var array $files
     */
    public $files = [];

    /**
     * метод определяет правила валидации
     * @return array
     */

    /**
     * @var string $document_file
     */
    public $document_file;


    public function rules()
    {
        return array_merge([
           // [['title'], 'required'], //, 'description'
           // ['title', 'string', 'min' => 3],
            //[['is_repeatable', 'is_blocking'], 'boolean'],
            ['email', 'email'],
          //  [['picture'], 'image', 'maxFiles' => 10],
          //  ['document_file', 'file', 'extensions' => ['pdf'], 'skipOnError' => false]

        ], parent::rules());
    }

    public function behaviors()
    {
        //return parent::behaviors(); // TODO: Change the autogenerated stub

        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['date_created', 'date_changed'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['date_changed'],
                ],
                'value' => new Expression('NOW()')
            ],
        ];
    }



    /**
     * @method
     * Возвращает массив меток полей формы
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'picture'  => \Yii::t('app', 'Add images'),
            'document' => \Yii::t('app', 'Add a file (pdf only)'),
            'userName' => \Yii::t('app', 'User name'),
            //'username' => \Yii::t('app', 'User name'),
        ];
    }


    // Геттер для имени пользователя

    /**
     * @return string
     */
    public function getUserName() {
        return $this->users->username;
    }
    /**
     * @return string
     */
    // Геттер название права доступа
    public function getAuthName() {
        return $this->getAuth()->item_name;
    }


    //public function upload()
    //{
    //    if ($this->validate()) {//
    //        $path = \Yii::getAlias('@app/uploads/');
    //        if (!FileHelper::createDirectory($path)) {
    //            throw new HttpException('Не удалось создать папку по адресу ' . $path);
    //        }
//
    //        //$file_name = $path . 'doc_' . date('d-m-Y', time()) . '.' . $this->document->extension;
//
    //        if (
    //        $this->document->saveAs($path . 'doc_' . date('d-m-Y', time()) . '.' . $this->document->extension)
    //        ) {
    //            //$this->files = $file_name;
//
    //            return true;
    //        } else
    //            return false;
//
    //    }
    //}






}
